export const DsrReportdatas = {
    "Token": "",
    "Message": "SUCCESS",
    "columns": [
      "SERVICE",
      "ORDER NO",
      "STATUS",
      "BOOKING NO",
      "BOOKING DATE",
      "ORIGIN",
      "POL",
      "POD",
      "FINAL DESTINATION",
      "CARGO READY DATE",
      "PICKUP DATE",
      "CARGO RECEIVED DATE",
      "ETD ORIGIN",
      "CONNECTION ETA",
      "CONNECTION ETD",
      "ETA DESTINATION",
      "HOUSE NO",
      "TERMS",
      "VESSEL CARRIER",
      "SHIPPER NAME",
      "CONSIGNEE NAME",
      "BILLING PARTY",
      "IMPORT EXPORT",
      "PCS",
      "WEIGHT",
      "VOLUME",
      "SHIPPER INVOICE_NO",
      "CONTAINER NO",
      "CONTAINER DETAILS",
      "CAN DATE",
      "DO NUMBER",
      "DO DATE",
      "SHIPPER REFERENCE NUMBER",
      "IGM/GIGM NO",
      "IGM/GIGM DATE",
      "LIGM NO",
      "LIGM DATE",
      "HBL/HAWB RELEASED DATE",
      "PRE ALERT DATE",
      "FRT INVOICE NO",
      "FRT INVOICE DATE",
      "SHIPPER INVOICE_VALUE",
      "CARRIER BOOKING_NO",
      "CARRIER BOOKING_DATE",
      "DIRECT BL",
      "BRAND ",
      "DIVISION ",
      "CHA ",
      "CONCEPT NAME",
      "SHIPMENT INTENDED_DATE",
      "NAC NAME",
      "CHECKLIST ADVISED",
      "CHECKLIST APPROVED",
      "DUTY ADVISED",
      "DUTY SUBMITTED",
      "BOND SENT TO CUSTOMER",
      "BOND RECVD FROM CUSTOMER",
      "BOND DATE",
      "LICENCE NO",
      "LICENCE DATE",
      "REMARKS LATEST UPDATE",
      "SUBJOB UID",
      "SLA STATUS"
    ],
    "data": [
      {
        "ORDER NO": "3PD0000421",
        "SUPPLIER NAME": "DONGGUAN JIN RONG TEXTILE FACTORY",
        "CONSIGNEE NAME": "TEST CUSTOMER FOR CALL ENTRY FROM TAB",
        "ORIGIN": "SHANGHAI",
        "DESTINATION": "JEBEL ALI(DUBAI)",
        "ORDER PCS": "45",
        "IN TRANSIT PCS": "45",
        "DELIVERED PCS": "",
        "PENDING PCS": ""
      },
      {
        "ORDER NO": "3PD0000422",
        "SUPPLIER NAME": "DONGGUAN JIN RONG TEXTILE FACTORY",
        "CONSIGNEE NAME": "TEST CUSTOMER FOR CALL ENTRY FROM TAB",
        "ORIGIN": "JEBEL ALI(DUBAI)",
        "DESTINATION": "SHANGHAI",
        "ORDER PCS": "10",
        "IN TRANSIT PCS": "",
        "DELIVERED PCS": "",
        "PENDING PCS": "10"
      },
      {
        "ORDER NO": "PI NO. 6686 - PO # 1416987",
        "SUPPLIER NAME": "TARRAGO BRANDS INTERNATIONAL, S.L.",
        "CONSIGNEE NAME": "RNA RESOURCES GROUP LTD",
        "ORIGIN": "JEBEL ALI(DUBAI)",
        "DESTINATION": "BARCELONA",
        "ORDER PCS": "1",
        "IN TRANSIT PCS": "",
        "DELIVERED PCS": "",
        "PENDING PCS": "1"
      }
    ]
  }