export const SHIPMENT_COUNT_REQUEST = 'SHIPMENT_COUNT_REQUEST';
export const SHIPMENT_COUNT_SUCCESS = 'SHIPMENT_COUNT_SUCCESS';
export const SHIPMENT_COUNT_FAILURE = 'SHIPMENT_COUNT_FAILURE';


export const SHIPMENT_HISTORY_REQUEST = 'SHIPMENT_HISTORY_REQUEST';
export const SHIPMENT_HISTORY_SUCCESS = 'SHIPMENT_HISTORY_SUCCESS';
export const SHIPMENT_HISTORY_FAILURE = 'SHIPMENT_HISTORY_FAILURE';

export const INBOX_COUNT_REQUEST = 'INBOX_COUNT_REQUEST';
export const INBOX_COUNT_SUCCESS = 'INBOX_COUNT_SUCCESS';
export const INBOX_COUNT_FAILURE = 'INBOX_COUNT_FAILURE';

export const SAILING_REQUEST = 'SAILING_REQUEST';
export const SAILING_SUCCESS = 'SAILING_SUCCESS';
export const SAILING_FAILURE = 'SAILING_FAILURE';

export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_SUCCESS = 'TODO_SUCCESS';
export const TODO_FAILURE = 'TODO_FAILURE';

export const BOOKING_REQUEST = 'BOOKING_REQUEST';
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS';
export const BOOKING_FAILURE = 'BOOKING_FAILURE';

export const PORT_REQUEST = 'PORT_REQUEST';
export const PORT_SUCCESS = 'PORT_SUCCESS';
export const PORT_FAILURE = 'PORT_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const OPENSAILING_REQUEST = 'OPENSAILING_REQUEST';
export const OPENSAILING_SUCCESS = 'OPENSAILING_SUCCESS';
export const OPENSAILING_FAILURE = 'OPENSAILING_FAILURE';

export const MAP_REQUEST = 'MAP_REQUEST';
export const MAP_SUCCESS = 'MAP_SUCCESS';
export const MAP_FAILURE = 'MAP_FAILURE';

export const VIEW_BOOKING_REQUEST = 'VIEW_BOOKING_REQUEST';
export const VIEW_BOOKING_SUCCESS = 'VIEW_BOOKING_SUCCESS';
export const VIEW_BOOKING_FAILURE = 'VIEW_BOOKING_FAILURE';

export const UPLOAD_DOCUMENT_REQUEST = 'UPLOAD_DOCUMENT_REQUEST';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAILURE = 'UPLOAD_DOCUMENT_FAILURE';

export const CANCEL_BOOKING_REQUEST = 'CANCEL_BOOKING_REQUEST';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAILURE = 'CANCEL_BOOKING_FAILURE';

export const QUOTATION_REQUEST = 'QUOTATION_REQUEST';
export const QUOTATION_SUCCESS = 'QUOTATION_SUCCESS';
export const QUOTATION_FAILURE = 'QUOTATION_FAILURE';

export const QUOTATION_DOWNLOAD_REQUEST = 'QUOTATION_DOWNLOAD_REQUEST';
export const QUOTATION_DOWNLOAD_SUCCESS = 'QUOTATION_DOWNLOAD_SUCCESS';
export const QUOTATION_DOWNLOAD_FAILURE = 'QUOTATION_DOWNLOAD_FAILURE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const DSR_REPORT_REQUEST = 'DSR_REPORT_REQUEST';
export const DSR_REPORT_SUCCESS = 'DSR_REPORT_SUCCESS';
export const DSR_REPORT_FAILURE = 'DSR_REPORT_FAILURE';

export const SAVE_DSR_REQUEST = 'SAVE_DSR_REQUEST';
export const SAVE_DSR_SUCCESS = 'SAVE_DSR_SUCCESS';
export const SAVE_DSR_FAILURE = 'SAVE_DSR_FAILURE';

export const DSR_DOWNLOAD_REQUEST = 'DSR_DOWNLOAD_REQUEST';
export const DSR_DOWNLOAD_SUCCESS = 'DSR_DOWNLOAD_SUCCESS';
export const DSR_DOWNLOAD_FAILURE = 'DSR_DOWNLOAD_FAILURE';

export const DSR_SCHEDULE_REQUEST = 'DSR_SCHEDULE_REQUEST';
export const DSR_SCHEDULE_SUCCESS = 'DSR_SCHEDULE_SUCCESS';
export const DSR_SCHEDULE_FAILURE = 'DSR_SCHEDULE_FAILURE';

export const NOTIFICATION_REQUEST = 'NOTIFICATION_REQUEST';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';

export const ALL_PORT_REQUEST = 'ALL_PORT_REQUEST';
export const ALL_PORT_SUCCESS = 'ALL_PORT_SUCCESS';
export const ALL_PORT_FAILURE = 'ALL_PORT_FAILURE';

export const FIND_NEW_RATE_REQUEST = 'FIND_NEW_RATE_REQUEST';
export const FIND_NEW_RATE_SUCCESS = 'FIND_NEW_RATE_SUCCESS';
export const FIND_NEW_RATE_FAILURE = 'FIND_NEW_RATE_FAILURE';

export const PICKUP_REQUEST = 'PICKUP_REQUEST';
export const PICKUP_SUCCESS = 'PICKUP_SUCCESS';
export const PICKUP_FAILURE = 'PICKUP_FAILURE';

export const DELIVERY_REQUEST = 'DELIVERY_REQUEST';
export const DELIVERY_SUCCESS = 'DELIVERY_SUCCESS';
export const DELIVERY_FAILURE = 'DELIVERY_FAILURE';

export const CONTAINER_PACK_REQUEST = 'CONTAINER_PACK_REQUEST';
export const CONTAINER_PACK_SUCCESS = 'CONTAINER_PACK_SUCCESS';
export const CONTAINER_PACK_FAILURE = 'CONTAINER_PACK_FAILURE';

export const INVOICE_CASH_REQUEST = 'INVOICE_CASH_REQUEST';
export const INVOICE_CASH_SUCCESS = 'INVOICE_CASH_SUCCESS';
export const INVOICE_CASH_FAILURE = 'INVOICE_CASH_FAILURE';

export const LOG_REQUEST = 'LOG_REQUEST';
export const LOG_SUCCESS = 'LOG_SUCCESS';
export const LOG_FAILURE = 'LOG_FAILURE';

export const FORGETPSWD_REQUEST = 'FORGETPSWD_REQUEST';
export const FORGETPSWD_SUCCESS = 'FORGETPSWD_SUCCESS';
export const FORGETPSWD_FAILURE = 'FORGETPSWD_FAILURE';