export const datas = [
    {
      
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:1,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:2,
      mode: "AIR",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:3,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:4,
      mode: "FCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:5,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:6,
      mode: "AIR",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:7,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:8,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:9,
      mode: "FCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:10,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
    {
      id:11,
      mode: "LCL",
      shipper: "GLOBAL CO.LTD",
      consignee: "INDIA AUTOMOBILE LTD",
      pol: "NHAVA SHEVA",
      pod: "JEBEL ALI",
      commodity: "Automotive ssss",
    },
  ];